### ISSUE TITLE
Indexes are not ensured

### ISSUE THREAD

**Issue by gjuchault** [neumino/thinky#319]
Hi,

I'm having a problem when I try to ensure indexes. I have ~50 indexes and at least the same number of relationships. That make a lot of indexes.

When I'm creating models, I wait for them to be ready with `model.on('ready')` to be sure everything is ready to be used.

Fact is, I need to restart at least 6 or 7 times the server to make sure indexes are created. I don't know how to provide you a decent and simple example to replicate (but the original code is [there](https://github.com/buckutt/Eve-Server/tree/master/src/models)).

I can attach a screen cast showing for example that the promise is triggered when calling `ensureIndex` and the index not be created in RethinkDB.

I looked into the code and saw that (`lib/model.js` at line 343) :
```js
      return r.branch(
        r.table(tableName).indexList().contains(name),
        r.table(tableName).indexWait(name),
        r.branch(
          r.table(tableName).info()('primary_key').eq(name),
          r.table(tableName).indexWait(name),
          r.table(tableName).indexCreate(name, fn, opts).do(function() {
            if (model._name === 'Article' && name === 'pointId') console.log(model._name, 'create index', name);
            return r.table(tableName).indexWait(name);
          })
        )
      )
      .run()
      .then(resolve)
      .error(function(error) {
        if (error.message.match(/^Index/)) {
          // TODO: This regex seems a bit too generous since messages such
          // as "Index `id` was not found on table..." will be accepted.
          // Figure out if this is OK or not.
          return resolve();
        }
        reject(error);
      });
```

I made some tests here and; there is a lot of errors passing in the `resolve` from `.error`. Theses errors are something like `Index not found` (exactly what you put in comment).

What's the solution here ? Is the regex trick the problem ?

**Comment by gjuchault** [comment]
Just to be clear : starting the server once make some indexes, then every `ready` event has been triggered so the server is considered ready (but it's not*); and every time I restart the server, some more indexes are made; until they are all made and the `ready` event are instant.

* If I start tests or make some request, I have errors when using indexes because they do not exist

**Comment by neumino** [comment]
Fixed in 2.1.4

The problem happened during the last refactoring...

**Comment by gjuchault** [comment]
@neumino Hm, just upgraded and the problem is still here.
I have the impression that when one index is created, Model emits the ready event. I'm looking into the code to understand what's happening

**Comment by gjuchault** [comment]
I did managed to make a reproduction script anyway :

```js
var thinky = require('thinky')({
    db: 'test'
});

var numberOfIndexes = 30;

var modelSchema = {};

for (var i = 0; i < numberOfIndexes; i++) {
    modelSchema['a' + i] = String;
}

var Model = thinky.createModel('Model', modelSchema);

for (var i = 0; i < numberOfIndexes; i++) {
    Model.ensureIndex('a' + i);
}

Model.on('ready', function () {
    thinky.r.table('Model').indexList().then(function (list) {
        console.log('Indexes created :', list);
        process.exit(0);
    });
});
```

I exit the process to be sure it doesn't continue to make indexes after (it doesn't, but this is just to be sure).

**Comment by neumino** [comment]
Thank you @gjuchault for testing it and providing a script.

That seems to be a bug in RethinkDB, `indexCreate` seems to silently fail. I opened https://github.com/rethinkdb/rethinkdb/issues/4698

**Comment by primitive-type** [comment]
I'm not 100% sure this is related, but I think it is. After upgrading to thinky 2.1.4 and RethinkDB 2.1.1 I now get the following type of error in abundance while running my tests:

```
Possibly unhandled ReqlOpFailedError: The server(s) hosting table `test.User_id` are currently unreachable. The secondary index was not created in:
r.branch(r.table("Group_User_teacher").indexList().contains("User_id"), r.table("Group_User_teacher").indexWait("User_id"), r.table("Group_User_teacher").indexCreate("User_id").do(function() {  
    return r.table("Group_User_teacher").indexWait("User_id")
})).do(function() {
    return r.branch(r.table("Group_User_teacher").indexList().contains("Group_id"), r.table("Group_User_teacher").indexWait("Group_id"), r.table("Group_User_teacher").indexCreate("Group_id").do(function() {
        return r.table("Group_User_teacher").indexWait("Group_id")
    }))
})

    at Connection._processResponse (/usr/src/app/node_modules/thinky/node_modules/rethinkdbdash/lib/connection.js:229:19)
    at Socket.<anonymous> (/usr/src/app/node_modules/thinky/node_modules/rethinkdbdash/lib/connection.js:150:14)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:521:20)
```

**Comment by neumino** [comment]
@primitive-type -- it seems slightly different.

How many servers do you have in your cluster? What probably happens is more lire
- We create a table
- We immediately try to create an index but the table is not available yet

**Comment by neumino** [comment]
Hum I just ran a script that create 10 tables at the same time and then immediately create an index on each and repeat.
It currently has 1500 tables and I couldn't get your error @primitive-type. How often does it happen for you?

**Comment by MarkHerhold** [comment]
I am not positive that this is related, but I have a similar issue after calling indexCreate() or ensureIndex() in my tests.
```
ReqlOpFailedError: Index `applicationId` was not found on table `test_11194.Metric` in:
r.table("Metric").getAll("Thing", {
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    index: "applicationId"
    ^^^^^^^^^^^^^^^^^^^^^^
})
^^
```

Thinky v2.1.4
One server in cluster (it's a test DB running locally)

**Comment by neumino** [comment]
Yea this is the same issue. A fix was pushed in RethinkDB todayso it will probably be soon released.

**Comment by primitive-type** [comment]
@neumino Sorry it took me so long to get back to you. Yeah, this happens every time I run my tests. Similar to @MarkHerhold I only have one server in my cluster and it's a test DB running locally that is emptied and repopulated upon each test in my app.

**Comment by neumino** [comment]
@primitive-type -- could you open a new issue for your problem? It seems different.

I have a few questions too:
- What OS are you using?
- How many tables/relations (roughly)?
- Is it a cold start (i.e with a new database)?

**Comment by primitive-type** [comment]
@neumino I am pretty my issue is just a duplicate of https://github.com/rethinkdb/rethinkdb/issues/4723

I'm also experiencing the issue that @MarkHerhold mentioned above, but as you noted that should be resolved by https://github.com/rethinkdb/rethinkdb/issues/4694

Sorry for the confusion. I will probably downgrade to RethinkDB 2.0.4 in the meantime.

**Comment by MarkHerhold** [comment]
[2.1.2 is out](https://github.com/rethinkdb/rethinkdb/releases/tag/v2.1.2) and tests are passing! Horray!

+1 for closing

**Comment by gjuchault** [comment]
Indeed, the last release fixes this
